# Generated by Django 5.1.5 on 2025-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('party_symbol', models.ImageField(upload_to='party_symbols/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
