# Generated by Django 5.1.5 on 2025-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_id',
        ),
    ]
